/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.foxymq;

import org.junit.Test;
import static org.junit.Assert.*;

import org.foxymq.connection.Connection;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        
        MsgTest msg = new MsgTest();
        msg.setAge((byte) 12);
        
        IConnection connection = Connection.makeConnection("localhost", 8080);
        connection.start

    }
}
